# Generated by Django 4.1.4 on 2022-12-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Panel',
            new_name='Iteam',
        ),
    ]
