# Generated by Django 4.1.4 on 2022-12-17 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0002_rename_panel_iteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteam',
            options={'verbose_name': 'Создать пост', 'verbose_name_plural': 'Создать посты'},
        ),
        migrations.AddField(
            model_name='iteam',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iteam',
            name='content',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='iteam',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='iteam',
            name='data_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
