# Generated by Django 4.1.4 on 2022-12-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_iteam_options_iteam_author_iteam_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteam',
            name='author',
        ),
    ]
