# Generated by Django 4.1.4 on 2022-12-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_iteam_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteam',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
