# Generated by Django 4.1.4 on 2022-12-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_iteam_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteam',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
